/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package forms.book;

import entities.Book;
import forms.ButtonHeaderRenderer;
import forms.CheckBoxRenderer;
import forms.Renderer;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author AAA
 */
public class BookPanel extends javax.swing.JPanel {

     private JFrame parentFrame;
     private BookTableModel modelBooks;
     private JTable tableBooks;
     TableRowSorter<TableModel> sorter;
     
     private List<Book> list;
     
    /**
     * Creates new form BookPanel
     */
    public BookPanel(JFrame frame, List<Book> list) {
        parentFrame = frame;
        this.list = list;
        initComponents();
        init();
    }
    
    private void init()
    {
        modelBooks = new BookTableModel(list);
        tableBooks = new JTable(modelBooks);
        jScrollPane1.setViewportView(tableBooks);
        
        tableBooks.setRowHeight(30);
        tableBooks.getColumnModel().getColumn(0).setMaxWidth(0);
        tableBooks.getColumnModel().getColumn(0).setMinWidth(0);
        tableBooks.getColumnModel().getColumn(0).setPreferredWidth(0);
        
        ButtonHeaderRenderer bhRenderer = new ButtonHeaderRenderer();
        for (int i = 0; i < tableBooks.getColumnModel().getColumnCount(); i++)
            tableBooks.getColumnModel().getColumn(i).setHeaderRenderer(bhRenderer);
        tableBooks.getTableHeader().setReorderingAllowed(false);
        
        Renderer renderer = new Renderer();
        CheckBoxRenderer chRenderer = new CheckBoxRenderer();
        for (int i = 0; i < tableBooks.getColumnModel().getColumnCount(); ++i)
            if (tableBooks.getColumnClass(i).equals(Boolean.class))
                tableBooks.getColumnModel().getColumn(i).setCellRenderer(chRenderer);
            else
                tableBooks.getColumnModel().getColumn(i).setCellRenderer(renderer);
        sorter = new TableRowSorter<TableModel>(modelBooks);
        tableBooks.setRowSorter(sorter);
        RowSorter.SortKey sortByAuthor = new RowSorter.SortKey(2, SortOrder.ASCENDING);
        RowSorter.SortKey sortByName = new RowSorter.SortKey(1, SortOrder.ASCENDING);
        sorter.toggleSortOrder(sortByName.getColumn());
        sorter.toggleSortOrder(sortByAuthor.getColumn());
    }

    public void refresh()
    {
        modelBooks.fireTableDataChanged();
        tableBooks.repaint();
    }
    
    public Book getSelectedBook()
    {
        if (tableBooks.getSelectedRow() == -1)
            return null;
        else
            return (Book)tableBooks.getValueAt(tableBooks.getSelectedRow(), 0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();

        setLayout(new java.awt.BorderLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(488, 600));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Книги");
        jPanel5.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel6.setPreferredSize(new java.awt.Dimension(488, 35));
        jPanel6.setLayout(new java.awt.GridLayout());

        jButton1.setText("Создать");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1);

        jButton2.setText("Редактировать");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2);

        jButton3.setText("Удалить");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3);

        jPanel3.add(jPanel6, java.awt.BorderLayout.PAGE_END);
        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        BookDialog dialog = new BookDialog(parentFrame);
        Book b = new Book();
        dialog.fill(b);
        dialog.setVisible(true);
        if (dialog.isSaved())
        {
            b = dialog.getBook();
            List list = modelBooks.getList();
            list.add(b);
            modelBooks.setList(list);
            modelBooks.fireTableDataChanged();
            tableBooks.repaint();
            int row = 0;
            for(int i = 0; i < tableBooks.getRowCount(); ++i)
            if (tableBooks.getValueAt(i, 0) == b)
            {
                row = i;
                break;
            }
            tableBooks.setRowSelectionInterval(row, row);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (tableBooks.getSelectedRow() > -1)
        {
            BookDialog dialog = new BookDialog(parentFrame);
            int row = tableBooks.getSelectedRow();
            Book b = (Book)tableBooks.getValueAt(row, 0);
            dialog.fill(b);
            dialog.setVisible(true);
            if (dialog.isSaved())
            {
                b = dialog.getBook();
                List list = modelBooks.getList();
                list.set(sorter.convertRowIndexToModel(row), b);
                modelBooks.setList(list);
                modelBooks.fireTableDataChanged();
                tableBooks.repaint();
                
                row = 0;
                for(int i = 0; i < tableBooks.getRowCount(); ++i)
                if (tableBooks.getValueAt(i, 0) == b)
                {
                    row = i;
                    break;
                }
                tableBooks.setRowSelectionInterval(row, row);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (tableBooks.getSelectedRow() > -1)
        {
            int row = tableBooks.getSelectedRow();
            List list = modelBooks.getList();
            list.remove(sorter.convertRowIndexToModel(row));
            modelBooks.setList(list);
            modelBooks.fireTableDataChanged();
            tableBooks.repaint();
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}