/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package forms.appeal;

import entities.Appeal;
import forms.ButtonHeaderRenderer;
import forms.CheckBoxRenderer;
import forms.MainForm;
import forms.Renderer;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JTable;

/**
 *
 * @author AAA
 */
public class AppealPanel extends javax.swing.JPanel {

     private JFrame parentFrame;
     private AppealTableModel modelAppeals;
     private JTable tableAppeals;
     
     private List<Appeal> list;
     
    /**
     * Creates new form BookPanel
     */
    public AppealPanel(JFrame frame, List<Appeal> list) {
        parentFrame = frame;
        this.list = list;
        initComponents();
        init();
    }
    
    private void init()
    {
        modelAppeals = new AppealTableModel(list);
        tableAppeals = new JTable(modelAppeals);
        jScrollPane1.setViewportView(tableAppeals);
        
        tableAppeals.setRowHeight(30);
        tableAppeals.getColumnModel().getColumn(0).setMaxWidth(0);
        tableAppeals.getColumnModel().getColumn(0).setMinWidth(0);
        tableAppeals.getColumnModel().getColumn(0).setPreferredWidth(0);
        
        ButtonHeaderRenderer bhRenderer = new ButtonHeaderRenderer();
        for (int i = 0; i < tableAppeals.getColumnModel().getColumnCount(); i++)
            tableAppeals.getColumnModel().getColumn(i).setHeaderRenderer(bhRenderer);
        tableAppeals.getTableHeader().setReorderingAllowed(false);
        
        Renderer renderer = new Renderer();
        CheckBoxRenderer chRenderer = new CheckBoxRenderer();
        for (int i = 0; i < tableAppeals.getColumnModel().getColumnCount(); ++i)
            if (tableAppeals.getColumnClass(i).equals(Boolean.class))
                tableAppeals.getColumnModel().getColumn(i).setCellRenderer(chRenderer);
            else
                tableAppeals.getColumnModel().getColumn(i).setCellRenderer(renderer);
    }
    
    public void refresh()
    {
        modelAppeals.fireTableDataChanged();
        tableAppeals.repaint();
        jButton1.setText(String.format("%.2f", ((MainForm)parentFrame).getLibrary().getProfit()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();

        setLayout(new java.awt.BorderLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(488, 600));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Обращения");
        jPanel5.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel6.setPreferredSize(new java.awt.Dimension(488, 35));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        jButton2.setText("Редактировать");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Сумма");
        jPanel6.add(jButton1);

        jPanel3.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        jScrollPane1.setForeground(new java.awt.Color(0, 255, 0));
        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (tableAppeals.getSelectedRow() > -1)
        {
            int row = tableAppeals.getSelectedRow();
            Appeal app = (Appeal)tableAppeals.getValueAt(row, 0);
            if (!app.isReturned())
            {
                AppealDialog dialog = new AppealDialog(parentFrame);
                dialog.fill(app);
                dialog.setVisible(true);
                if (dialog.isSaved())
                {
                    app = dialog.getAppeal();
                    List list = modelAppeals.getList();
                    list.set(row, app);
                    modelAppeals.setList(list);
                    modelAppeals.fireTableDataChanged();
                    tableAppeals.repaint();
                    tableAppeals.setRowSelectionInterval(row, row);
                    if (app.isReturned())
                    {
                        jButton1.setText(String.format("%.2f", ((MainForm)parentFrame).getLibrary().getProfit()));
                        ((MainForm)parentFrame).getBookPanel().refresh();
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}