/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package forms.reader;

import entities.Reader;
import forms.ButtonHeaderRenderer;
import forms.MainForm;
import forms.Renderer;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author AAA
 */
public class ReaderPanel extends javax.swing.JPanel {

     private JFrame parentFrame;
     private ReaderTableModel modelReaders;
     private JTable tableReaders;
     TableRowSorter<TableModel> sorter;
     
     private List<Reader> list;
     
    /**
     * Creates new form BookPanel
     */
    public ReaderPanel(JFrame frame, List<Reader> list) {
        parentFrame = frame;
        this.list = list;
        initComponents();
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ((MainForm)frame).takeBook();
            }
        });
        
        init();
    }
    
    private void init()
    {
        modelReaders = new ReaderTableModel(list);
        tableReaders = new JTable(modelReaders);
        jScrollPane1.setViewportView(tableReaders);
        
        tableReaders.setRowHeight(30);
        tableReaders.getColumnModel().getColumn(0).setMaxWidth(0);
        tableReaders.getColumnModel().getColumn(0).setMinWidth(0);
        tableReaders.getColumnModel().getColumn(0).setPreferredWidth(0);
        
        ButtonHeaderRenderer bhRenderer = new ButtonHeaderRenderer();
        for (int i = 0; i < tableReaders.getColumnModel().getColumnCount(); i++)
            tableReaders.getColumnModel().getColumn(i).setHeaderRenderer(bhRenderer);
        tableReaders.getTableHeader().setReorderingAllowed(false);
        
        Renderer renderer = new Renderer();
        for (int i = 0; i < tableReaders.getColumnModel().getColumnCount(); ++i)
            tableReaders.getColumnModel().getColumn(i).setCellRenderer(renderer);
        sorter = new TableRowSorter<TableModel>(modelReaders);
        tableReaders.setRowSorter(sorter);
        RowSorter.SortKey main = new RowSorter.SortKey(1, SortOrder.ASCENDING);
        sorter.toggleSortOrder(main.getColumn());
    }

    public Reader getSelectedReader()
    {
        if (tableReaders.getSelectedRow() == -1)
            return null;
        else
            return (Reader)tableReaders.getValueAt(tableReaders.getSelectedRow(), 0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();

        setLayout(new java.awt.BorderLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(488, 600));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Читатели");
        jPanel5.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel6.setPreferredSize(new java.awt.Dimension(488, 35));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setText("Создать");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1);

        jButton2.setText("Редактировать");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2);

        jButton3.setText("Удалить");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3);

        jButton4.setBackground(new java.awt.Color(224, 224, 224));
        jButton4.setText("Взять книгу");
        jPanel6.add(jButton4);

        jPanel3.add(jPanel6, java.awt.BorderLayout.PAGE_END);
        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ReaderDialog dialog = new ReaderDialog(parentFrame);
        Reader r = new Reader();
        dialog.fill(r);
        dialog.setVisible(true);
        if (dialog.isSaved())
        {
            r = dialog.getReader();
            List list = modelReaders.getList();
            list.add(r);
            modelReaders.setList(list);
            modelReaders.fireTableDataChanged();
            tableReaders.repaint();
            int row = 0;
            for(int i = 0; i < tableReaders.getRowCount(); ++i)
            if (tableReaders.getValueAt(i, 0) == r)
            {
                row = i;
                break;
            }
            tableReaders.setRowSelectionInterval(row, row);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (tableReaders.getSelectedRow() > -1)
        {
            ReaderDialog dialog = new ReaderDialog(parentFrame);
            int row = tableReaders.getSelectedRow();
            Reader r = (Reader)tableReaders.getValueAt(row, 0);
            dialog.fill(r);
            dialog.setVisible(true);
            if (dialog.isSaved())
            {
                r = dialog.getReader();
                List list = modelReaders.getList();
                list.set(sorter.convertRowIndexToModel(row), r);
                modelReaders.setList(list);
                modelReaders.fireTableDataChanged();
                tableReaders.repaint();
                row = 0;
                for(int i = 0; i < tableReaders.getRowCount(); ++i)
                if (tableReaders.getValueAt(i, 0) == r)
                {
                    row = i;
                    break;
                }
                tableReaders.setRowSelectionInterval(row, row);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (tableReaders.getSelectedRow() > -1)
        {
            int row = tableReaders.getSelectedRow();
            List list = modelReaders.getList();
            list.remove(sorter.convertRowIndexToModel(row));
            modelReaders.setList(list);
            modelReaders.fireTableDataChanged();
            tableReaders.repaint();
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}